### PR TITLE
Rework SEQ (storage), add Luciole, add Dodo Labs

### PR DESCRIPTION
**Pull request by minchinweb**
These is designed to be a smaller, easier to review update. If you want it broken down even further (if that would make it easier), let me know.

What this does:

- adds [Luciole](https://forum.kerbalspaceprogram.com/topic/193010-1125-luciole-19/)
- adds [Dodo Labs](https://forum.kerbalspaceprogram.com/topic/177617-1101-dodo-labs-v131-stockalike-electron/)
- rework *SEQ* (storage containers)
- Allow 0.625m SRB's to have more than 100 fuel
- adjust some (previously overlooked) stock fuel tanks
- added the Stock 1.12.5 localization strings

### CODE REVIEW

**Comment by minchinweb** [comment]
P.S. I'd merge this myself (or future ones), but can I push a release to SpaceDock/CKAN? Does it pull it automatically if I create a GitHub release? I've never published to SpaceDock before...

**Comment by yalov** [comment]
I use [release.py](https://github.com/yalov/CommunityPartsTitles/blob/master/release.py) to release a new version to github and spacedock, but it use a private login, password and token, so it will not work for you.
CKAN updates automatically, based on the github releases. 


- remove please the commented descriptions from the Luciole to make it more clear
- do you have MakingHistory DLC? The last PR had missed some parts from there. 
Also Restock+ interferes with MakingHistory, so I was testing all combinations MH, Restock+, MH + Restock+

**Comment by minchinweb** [comment]
Done!

- I've remove the Luciole descriptions
- I've expanded the SEQ rework to some mod parts I'd previously missed

As for the DLC's, I actually just bought them, so I should catch any DLC parts going forward. I haven't done a full install without Restock+, but I did review their codebase and they don't seem to do anything with the storage containers, so I **don't** expect that (MH + Restock+) to be an issue here. But I'll look for that going forward!

I guess I'll leave releases to you then.

**Comment by yalov** [comment]
thanks, 
now I properly launch the game and review parts titles, there is next few remarks:

Dodo: 
you missed the engine shroud (it is convenient to use the Janitor Closet mod to quickly filter by a mod)

Luciole:
Probes: 
L-K firefly Kickstage — the crazy-ass probe+booster is missed.

fuel tanks
EO-06-30 while stock EO-06-020

RCS
thruct power is 0.1, so it should be near RV-01X, and not the RV-105 — RV-01XA or something — A for Advanced, because higher ISP

Structural
The adapter is for 0.125m stack size, so "Adapter 01-01x5" 

Aero
wing area 0.12 — AV-B1, so 
wing area 0.02 — AV-B02, 
you already use "/" as devider of 2 values, so to use it also as decimal separator is unintuitive.

Electical:
The same with "/" as decimal separator. I don't remember, there was some problem with the "." ?
Also all these static panels: KX-000/3, KX-003 looks too many zeros. Are there more than 100 EC/s static solar panels in mods? I don't remember.


antennas
I use [this ](https://forum.kerbalspaceprogram.com/topic/139980-130-community-database-of-module-manager-patches-for-stock-ksp/?do=findComment&comment=3510150) for a reference, so 125k is "C0+"

**Comment by minchinweb** [comment]
> Dodo:
> you missed the engine shroud (it is convenient to use the Janitor Closet mod to quickly filter by a mod)

I don't think we currently have a prefix for "engine shrouds". What do you suggest I put it under?

**Comment by yalov** [comment]
Thanks, 
I have merged everything before rework RCS blocks, because it demands separate PR. 
I will repeat the [Update as per comments](https://github.com/yalov/CommunityPartsTitles/pull/20/commits/d4e231fdde1cf5f9be9600f4c4853e204574fa68), you don't need to recreate this commit

**Comment by minchinweb** [comment]
Thanks!!

I had also thought to do the RCS blocks as a separate PR, but ran out of time to do that the other night. I've created #22 for RCS blocks.

**Pull request closed without merging**
