### PR TITLE
Big update!

### PR DESCRIPTION
**Pull request by minchinweb**
Hey Alexander!

After much time away from the game, I picked up KSP, downloaded too many mods, and tried to make sense of what was what, and turned to my CommunityPartsTitles to do that. Here's the update, with several additional mods and some expanded "namespaces":

Added:

- CactEye
- Lithobrake Exploration Technologies (LET)
- Mk2 Essentials (Recycled Parts)
- Mk2 Solar Batteries (Recycled Parts)
- Buffalo2
- Organi Foldable (Antennas) (Recycled Parts)
- Near Future Exploration
- USI Exploration
- USI Kolonization
- LanderTek
- Simple Cargo Solutions
- Tantares (limited)

Reworked / Expanded / Corrected:

- Space Y Lifters
- Space Y Expanded
- Squiggsy Space Research (MicroSat)
- Near Future (fuel tanks)

Reworked / New Namespaces:

- Z -- batteries
- AE-FF -- fairings
- TVR -- adapters
- SP / OX / KX -- solar panels
- SRB -- solid rocket boosters
- HS -- heat sheilds
- Nc / Nb / Nk -- parachutes
- Adapters

I also expanded the Naming Spec.

Feel free to ask any questions you might have.

(If for some reason you're not in a position to push out updates, that's fine too. Just let me know.)

### CODE REVIEW

**Comment by yalov** [comment]
Wow, thank you! I will review this, but no promises about releasing time, I have a lot of work now

**Comment by yalov** [comment]
hello, I have added you as collarator, so you should be able to accept pr, and make a release to this repo.

I am reviewing only the changes in diff, but not the new mods support, because I have not testplayed.

**solar:**
I am using UKEB, because originally in the mod they are OKEB, and making them SP and OX will force to add extra zero to 05, 07 that I do not like to do without a reason.

~~I am Using JX for large static, because It places them after the stock IX~~
I see, static are set to KX.


**structural adapters:**
I liked that they are all together and at the top. Is there a reason why you have changed it?


**Structural Tube and Protective Shell:**
I understand that you are doing.
Originally I put "do not change stock" as Convention /# 2, because I had not wanted to change staff without good reason.
Especially, if there is some stock order and grouping, and it is working without problems — I am using it but do not change it — it also gives some more "spice" to the naming without drawback. 
Also, I prefer do not change stuff without a reason, because otherwise I could break order or grouping of mods, that I do not support, and that built around this already existing stock pattern.

The last statement probably a little less important now, because there is no active mods scene for ksp1, and no future updates. 

There is reason why you have updated the Protective Shell?

**Comment by minchinweb** [comment]
> I have added you as [collaborator]

Thanks!

**Re Solar Panels**: Mostly, I was trying to separate out the solar panels that you can retract from the ones you can't. In the end, I had three categories: those that were surface mounted (*KX*), those that could be retracted (*SP*) and those that couldn't be retracted once deployed (*OX*). But I'm happy to use a different prefix. Is there a better way to sort them?

**Re Adapters**: The *TVR* prefix actually comes from stock parts (see [TVR-200 Stack Bi-Coupler](https://wiki.kerbalspaceprogram.com/wiki/TVR-200_Stack_Bi-Coupler)). But I'm happy to use *Adapter* as the "prefix", if you'd rather.

**Re Protective Shell**: (i.e. the change from "AE-FF1.5" to "AE-FF-18") I updated it because I couldn't remember what the "size" numbers were, and the things I was attaching it to (fuel tanks, but somethings decouplers or probe cores) were sized based on diameter. So the goal was to make it consistent with the other series.

**Comment by yalov** [comment]
yes, just leave the "Adapter" for structural adapters, like it was before.
Everything else is ok.

**Comment by minchinweb** [comment]
Adapters are now under "Adapter"!

Can you put out an update? (or would you like me to?)

**Pull request merged**
